[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "deephalo"
version = "1.0.0"
description = "Your package description here"
authors = [
    {name = "Your Name", email = "your@email.com"},
]
license = {text = "MIT"}  # or another license
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]


[project]
name = "deephalo"
version = "1.0.0"
description = "A Hierarchically Optimized Workflow 
for High-Confidence and High-throughput Detection 
of Halogenated Compounds in Complex HRMS Data"
authors = [
    {name = "Yunying Xie", email = "xieyy@imb.pumc.edu.cn"},
]
dependencies = [
        'pandas ==  2.0.3',
        'numpy ==  1.22.0',     
        'molmass ==  2023.8.30',
        'scikit-learn ==  1.3.1',    
        'tensorflow ==  2.10.1',
        'keras ==  2.10.0',     
        'keras_tuner ==  1.4.6',
        'matplotlib ==  3.8.0', 
        'pyopenms ==  3.1.0',   
        'scipy ==  1.11.4',  
        'tomli ==  2.0.1',
        'tomli-w ==  1.0.0',
        'importlib_resources == 6.4.0',
        'mzml2gnps == 1.0.3',
        'networkx == 3.4.2',
        'typer == 0.15.1',
]

readme = "README.md"

[project.scripts]
halo = "deephalo.halo_cli:app" # CLI entry point

[tool.setuptools.packages.find]
exclude = ["deephalo.test"]

[tool.setuptools.package-data]
# Include all configuration files
"deephalo" = ["*.toml"]
# Include all h5 files
"deephalo.assets.pretrained_models" = ["*.h5"]