#This section declares what are your build system dependencies, and which library will be used to actually do the packaging.
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "DeepHalo"
version = "0.9.1"
dependencies = [
        'pandas ==  2.0.3',
        'numpy ==  1.22.0',     
        'molmass ==  2023.8.30',
        'scikit-learn ==  1.3.1',    
        'tensorflow ==  2.10.1',
        'keras ==  2.10.0',     
        'keras_tuner ==  1.4.6',
        'matplotlib ==  3.8.0', 
        'pyopenms ==  3.1.0',   
        'scipy ==  1.11.4',  
        'tomli ==  2.0.1',
        'tomli-w ==  1.0.0',
        'importlib_resources == 6.4.0',
        'mzml2gnps == 1.0.3',
        'networkx == 3.4.2',
        'typer == 0.15.1',
]

readme = "README.md"

[project.scripts]
halo = "DeepHalo.command_line:app"

[tool.setuptools.packages.find]
exclude = ["DeepHalo.Test"]

[tool.setuptools.package-data]
# Include all configuration files
"DeepHalo" = ["*.toml"]
# Include all h5 files in the DeepHalo\model directory
"DeepHalo.models" = ["*.h5"]