#创建模型训练集相关参数
[datasets]
#数据库文件路径
paths = [


       [   "E:/XinBackup/source_data/datasets/NPAtlas_download.json",
        "mol_formula",
    ],
       

    ]
#训练集中所包含的元素种类
element_list = ['C','H','O','N','P','Cl','Br','F','I','Ho','Na','Al','As','S','Fe','Se','B','e-']
#质荷比范围
mz_start = 50
mz_end = 3000
#基于真是数据库生成的噪音数据量倍率
repeat_for_noise = 1
#模拟hydro所用的rate
rate_for_hydro = [0.33,0.66,0.99,1.32,1.65,1.99,2.3,4,5]

#模型训练参数
[model_data]
#训练使用的特征列表
feature_list = [
        'ints_b3',
        "ints_b_2",
        "ints_b_1",
        "ints_b0",
        "ints_b1",
        "ints_b2",
        "ints_b3",
        "m2_m1",
        "m1_m0",
        "b2_b1",
]
#训练使用的数据集
use_noise_data = "False"
use_add_fe_data = "True"
use_add_b_data =  "True"
use_add_se_data =  "True"
use_add_s_data  = "False"
use_hydroisomer_data = "True"

#模型训练参数
[model_construct]
train_batch = 256
val_batch = 256
classes = 8
epochs = 10
learning_rate = 0.0003

#模型训练权重
[model_construct_class_weight.classes_weight]

0 = 0.00814085
1 = 0.00691053
2 = 0.00504485
3 = 0.00803245
4 = 0.0078278
5 =  0.00809219
6 = 0.00342363
7 = 0.00270589

#使用asari进行峰识别的参数
[asari]
min_prominence_threshold = 0.33
mz_tolerance_ppm = 10
min_intensity = 5000
min_timepoints = 5
min_peak_height = 5000

#使用ms1ms2_linked进行峰识别的参数
[mzml]
vendor = ''
min_intensity = 100 #并非相对强度，An intensity threshold of 500  was used to eliminate electronic noise.
precursor_error = 0.8
ROI_identify_method = 'DDA' # MS:asari; DDA:ms2fms1;peak_only: ROI
min_element_roi = 3 #roi识别中MS1_index的最少元素数量
min_element_sum = 3 #halo_eval中count_list中最少元素数量

#可视化参数
[visualization]
path = "C:\\Users\\xyy\\Desktop\\python\\HaloAnalyzer_training\\test1"
