#创建模型训练集相关参数
[datasets]
#数据库文件路径
paths = [

       [   "D:/python/wangmengyuan/dataset/datasets/NPAtlas_download.json",
        "mol_formula",
    ],
   [
        "D:/python/wangmengyuan/dataset/datasets/CFM-ID_metadata_DTXCID.csv",
        "MS-Ready_Mol_Formula",
    ],
    [
        "D:/python/wangmengyuan/dataset/datasets/hmdb_metabolites.csv",
        "chemical_formula",
    ],
    [
        "D:/python/wangmengyuan/dataset/datasets/uniqueNaturalProduct_formula_from_COCONUT.csv",
        "Formula",
    ],
    [
        "D:/python/wangmengyuan/dataset/datasets/ZINC_merged_data_dereplicated.csv",
        "formula",
    ],
    [
        "D:/python/wangmengyuan/dataset/datasets/ChEBI_database.csv",
        "CHEMICAL_DATA",
    ],

    ]
#训练集中所包含的元素种类
element_list = ['C','H','O','N','P','Cl','Br','F','I','Ho','Na','Al','As','S','Fe','Se','B','e-']
#质荷比范围
mz_start = 50
mz_end = 3000
#基于真是数据库生成的噪音数据量倍率
repeat_for_noise = 1
#模拟hydro所用的rate
rate_for_hydro = [0.33,0.66,0.99,1.32,1.65,1.99,2.3,4,5]

#模型训练参数
[model_data]
#训练使用的特征列表
feature_list = [
    "ints_b_3",
    "ints_b_2",
    "ints_b_1",
    "ints_b0",
    "ints_b1",
    "ints_b2",
    "ints_b3",
    "m2_m1",
    "m1_m0",
    "b2_b1",
]
#训练使用的数据集
use_noise_data = "True"
use_add_fe_data = "True"
use_add_b_data =  "True"
use_add_se_data =  "True"
use_add_s_data  = "False"
use_hydroisomer_data = "True"

#模型训练参数
[model_construct]
train_batch = 1024
val_batch = 1024
classes = 8
epochs = 15
learning_rate = 0.0005

#模型训练权重
[model_construct_class_weight.classes_weight]
0 = 1.6
1 = 1.2
2 = 0.63
3 = 2.4
4 = 2.4
5 = 2.4
6 = 0.58
7 = 0.2

#使用asari进行峰识别的参数
[asari]
min_prominence_threshold = 0.33
mz_tolerance_ppm = 10
min_intensity = 5000
min_timepoints = 5
min_peak_height = 5000

#使用ms1ms2_linked进行峰识别的参数
[mzml]
vendor = ''
min_intensity = 100 #并非相对强度
precursor_error = 0.3
ROI_identify_method = 'DDA'
min_element_roi = 3 #roi识别中MS1_index的最少元素数量
min_element_sum = 3 #halo_eval中count_list中最少元素数量

#可视化参数
[visualization]
path = "C:\\Users\\xyy\\Desktop\\python\\HaloAnalyzer_training\\test1"
