#此文件为配置文件，用于配置模型训绨集相关参数

#mzml文件预测参数
[FeatureFinding]
mass_trace_detection = [["mass_error_ppm", 10.0], # default:20.0 # default:5.0 Change according to experiment conditions
                        ['min_trace_length', 1.0], # default：5.0 # default:5.0 Change according to experiment conditions
                        ['noise_threshold_int', 200.0], # not default # default:5.0 Change according to experiment conditions
                        ['chrom_peak_snr',3.0],
                        ['trace_termination_criterion', 'outlier'],
                        ['trace_termination_outliers', 5],
                        ['min_sample_rate', 0.5],
                        ['quant_method', 'area'],
                        ['reestimate_mt_sd', 'true'],
                        ['max_trace_length', -1.0],
                        ]

elution_peak_detection = [
                          ['chrom_fwhm', 3.0], # default:5.0
                          ['chrom_peak_snr',3.0],
                          ['width_filtering','fixed'],
                          ['min_fwhm',1.0],
                          ['max_fwhm',60.0],
                          ['masstrace_snr_filtering','false'],
                          ]

feature_detection = [['local_rt_range',10.0],
                     ['local_mz_range',5.5], # default 6.5 DeepHalo use 6 isotope peaks, so here set 5.5
                     ['chrom_fwhm', 1.0], # default:5.0 Change according to experiment conditions
                     ['charge_lower_bound', 1],
                     ['charge_upper_bound', 3],
                     ['charge_upper_bound', 3],
                     ['enable_RT_filtering', 'true'],
                     ['use_smoothed_intensities', 'true'],
                     ['mz_scoring_by_elements', 'true'], # not default for pyopenms,but manditory for DeepHalo
                     ['elements', 'CHNOPS'], 
                     ['report_chromatograms', 'false'],
                     ['isotope_filtering_model','none'], # not default for pyopenms, but manditory for DeepHalo
                     ['remove_single_traces', 'true'], # not deault for pyopenms, but manditory for DeepHalo
                     ['report_convex_hulls', 'true'] # not default for pyopenms, but manditory for DeepHalo
                     ]
# For details on the above parameters, please refer to pyopenms.

[FeatureMapProcessor]
min_num_of_masstraces = 3 # 含有卤素的化合物最好有3个同位素峰
min_feature_int = 10000  # the threshold for further halo-containing analysis. Here the intensity is the sum intensity of a candidate featrue.

#训练集相关参数
[datasets]

paths = [
 
        [   "D:/python/wangmengyuan/dataset/datasets/NPAtlas_download.json",
        "mol_formula",
     ],
    [
         "D:/python/wangmengyuan/dataset/datasets/CFM-ID_metadata_DTXCID.csv",
         "MS-Ready_Mol_Formula",
     ],
     [
         "D:/python/wangmengyuan/dataset/datasets/hmdb_metabolites.csv",
         "chemical_formula",
     ],
     [
         "D:/python/wangmengyuan/dataset/datasets/uniqueNaturalProduct_formula_from_COCONUT.csv",
         "Formula",
     ],
     [
         "D:/python/wangmengyuan/dataset/datasets/ZINC_merged_data_dereplicated.csv",
         "formula",
     ],
     [
         "D:/python/wangmengyuan/dataset/datasets/ChEBI_database.csv",
         "CHEMICAL_DATA",
     ],
 
]
#数据库文件路径
# type_list = ['base','Fe','B','Se','hydro']
type_list = ['base']
element_list = ['C','H','O','N','P','Cl','Br','F','I','S','Fe','Se','B']#训练集中所包含的元素种类
mz_start = 50#质荷比起始值
mz_end = 3000#质荷比终止值
rate_for_hydro = [0.33,0.66,0.99,1.32,1.65,2.3,5]#模拟hydro所用的rate
return_from_max_ints = "True"#是否从最大强度的峰开始返回

#模型训练参数
[model_data]
#训练使用的特征列表
feature_list = [
            "p0_int",
            "p1_int",
            "p2_int",
            "p3_int",
            "p4_int",
            "p5_int",
            "m2_m1",
            "m1_m0",   
        ]
#训练使用的数据集
use_add_fe_data = "True"
use_add_b_data =  "True"
use_add_se_data =  "True"
use_hydroisomer_data = "True"

#模型训练参数
[model_construct]
train_batch = 8
val_batch = 8
classes = 8
epochs = 10
learning_rate = 0.0003

#模型训练权重
[model_construct_class_weight.classes_weight]

0 = 1.31312866e-05 
1 = 9.63363294e-06
2 = 5.19189234e-06
3 = 1.96005410e-05
4 = 1.79784977e-05
5 = 2.00924252e-05
6 = 2.47260967e-06
7 = 2.87867535e-06

#可视化参数
[visualization]
path = "C:\\Users\\xyy\\Desktop\\python\\HaloAnalyzer_training\\test1"
