[datasets]
mz_start = 200
mz_end = 2000
element_list = [
    "K",
    "F",
    "S",
    "N",
    "C",
    "As",
    "P",
    "I",
    "O",
    "Cl",
    "H",
    "Br",
    "Ho",
    "Na",
    "Al",
]
repeat = 1
feature_list = [
    "new_a0_ints",
    "new_a1_ints",
    "new_a2_ints",
    "new_a2_ints",
    "new_a2_a1_10",
]
paths = [
    [
        "J:/wangmengyuan/dataset/datasets/NPAtlas_download.json",
        "mol_formula",
    ],
    [
        "J:/wangmengyuan/dataset/datasets/CFM-ID_metadata_DTXCID.csv",
        "MS-Ready_Mol_Formula",
    ],
    [
        "J:/wangmengyuan/dataset/datasets/hmdb_metabolites.csv",
        "chemical_formula",
    ],
    [
        "J:/wangmengyuan/dataset/datasets/uniqueNaturalProduct_formula_from_COCONUT.csv",
        "Formula",
    ],
    [
        "J:/wangmengyuan/dataset/datasets/ZINC_merged_data_dereplicated.csv",
        "formula",
    ],
    [
        "J:/wangmengyuan/dataset/datasets/ChEBI_database.csv",
        "CHEMICAL_DATA",
    ],
]

[model_data]
data_weight = 1
noise_data_weight = 1
use_noise_data = "True"
use_add_fe_data = "False"
use_hydroisomer_data = "True"

[model_construct]
train_batch = 1024
val_batch = 1024
dense1 = 2000
dense1_drop = 0.5
dense2 = 500
dense2_drop = 0.3
dense3 = 250
classes = 7
epochs = 5

[model_construct_class_weight.base_weight]
0 = 1
1 = 1
2 = 1

[model_construct_class_weight.sub_weight]
0 = 5
1 = 3
2 = 2
3 = 1

[model_construct_class_weight.hydroisomer_weight]
0 = 5
1 = 3
2 = 5
3 = 1
4 = 1
5 = 1
6 = 1

[asari]
min_prominence_threshold = 0.33
mz_tolerance_ppm = 10
min_intensity = 5000
min_timepoints = 5
min_peak_height = 5000

[mzml]
min_intensity = 1

[visualization]
path = "C:\\Users\\xyy\\Desktop\\python\\HaloAnalyzer_training\\test1"
