[datasets]
paths = [
    
    [   "J:/wangmengyuan/dataset/datasets/NPAtlas_download.json",
        "mol_formula",
    ],]
element_list = ['C','H','O','N','P','Cl','Br','F','I','Ho','Na','Al','As','S','Fe','Se','B','e-']
 
mz_start = 50
mz_end = 3000
repeat_for_noise = 1
rate_for_hydro = [0.33,0.66,0.99,1.32,1.65]

[model_data]
feature_list = [
    "ints_b3",
    "ints_b2",
    "ints_b1",
    "ints_a0",
    "ints_a1",
    "ints_a2",
    "ints_a3",
    "new_a2_a1_10",
]
use_noise_data = "False"
use_add_fe_data = "True"
use_add_b_data =  "True"
use_add_se_data =  "True"
use_add_s_data = "False"
use_hydroisomer_data = "True"

[model_construct]
train_batch = 256
val_batch = 256

classes = 8

epochs = 10
learning_rate = 0.001

[model_construct_class_weight.classes_weight]
0 = 1
1 = 1
2 = 2
3 = 1
4 = 1
5 = 1
6 = 1
7 = 1

[asari]
min_prominence_threshold = 0.33
mz_tolerance_ppm = 10
min_intensity = 5000
min_timepoints = 5
min_peak_height = 5000

[mzml]
vendor = ''
min_intensity = 100
precursor_error = 0.3
ROI_identify_method = 'ms1ms2_linked'

[visualization]
path = "C:\\Users\\xyy\\Desktop\\python\\HaloAnalyzer_training\\test1"
