[datasets]
mz_start = 200
mz_end = 2000
element_list = [
    "K",
    "F",
    "S",
    "N",
    "C",
    "As",
    "P",
    "I",
    "O",
    "Cl",
    "H",
    "Br",
    "Ho",
    "Na",
    "Al",
]
repeat = 1
feature_list = [
    "new_a0_ints",
    "new_a1_ints",
    "new_a2_ints",
    "new_a3_ints",
	"new_a2_a1",
	"new_a2_a0"
]
paths = [
    [
        "F:/XinBackup/source_data/datasets/NPAtlas_download.json",
        "mol_formula",
    ],
]

[model_data]
data_weight = 100
noise_data_weight = 1
add_fe_data_weight = 10
hydroisomer_data_weight = 10
use_noise_data = "False"
use_add_fe_data = "True"
use_hydroisomer_data = "True"

[model_construct]
train_batch = 1000
val_batch = 1000
dense1 = 4000
dense1_drop = 0.5
dense2 = 1000
dense2_drop = 0.3
dense3 = 250
base_classes = 3
sub_classes = 5
hydro_classes = 8
epochs = 10

[model_construct_class_weight.base_weight]
0 = 500
1 = 500
2 = 500

[model_construct_class_weight.sub_weight]
0 = 100
1 = 100
2 = 100
3 = 100

[model_construct_class_weight.hydroisomer_weight]
0 = 100
1 = 100
2 = 200
3 = 100
4 = 100
5 = 100
6 = 100

[asari]
min_prominence_threshold = 0.33
mz_tolerance_ppm = 10
min_intensity = 5000
min_timepoints = 5
min_peak_height = 5000

[mzml]
min_intensity = 100

[visualization]
path = "C:\\Users\\xyy\\Desktop\\python\\HaloAnalyzer_training\\test1"
