#此文件为配置文件，用于配置模型训绨集相关参数

#训练集相关参数
[datasets]

paths = [
            
       [   "D:/python/wangmengyuan/dataset/datasets/NPAtlas_download.json",
        "mol_formula",
    ],
   [
        "D:/python/wangmengyuan/dataset/datasets/CFM-ID_metadata_DTXCID.csv",
        "MS-Ready_Mol_Formula",
    ],
    [
        "D:/python/wangmengyuan/dataset/datasets/hmdb_metabolites.csv",
        "chemical_formula",
    ],
    [
        "D:/python/wangmengyuan/dataset/datasets/uniqueNaturalProduct_formula_from_COCONUT.csv",
        "Formula",
    ],
    [
        "D:/python/wangmengyuan/dataset/datasets/ZINC_merged_data_dereplicated.csv",
        "formula",
    ],
    [
        "D:/python/wangmengyuan/dataset/datasets/ChEBI_database.csv",
        "CHEMICAL_DATA",
    ],
    
           
        ]#数据库文件路径
element_list = ['C','H','O','N','P','Cl','Br','F','I','S','Fe','Se','B']#训练集中所包含的元素种类
mz_start = 50#质荷比起始值
mz_end = 3000#质荷比终止值
rate_for_hydro = [0.33,0.66,0.99,1.32,1.65,2.3,5]#模拟hydro所用的rate
return_from_max_ints = "True"#是否从最大强度的峰开始返回

#模型训练参数
[model_data]
#训练使用的特征列表
feature_list = [
            "ints_0",
            "ints_1",
            "ints_2",
            "ints_3",
            "ints_4",
            "ints_5",
            "ints_6",
            "m2_m1",
            "m1_m0",   
        ]

#训练使用的数据集
use_add_fe_data = "True"
use_add_b_data =  "True"
use_add_se_data =  "True"
use_hydroisomer_data = "True"

#模型训练参数
[model_construct]
train_batch = 4
val_batch = 4
classes = 8
epochs = 20
learning_rate = 0.0003

#模型训练权重
[model_construct_class_weight.classes_weight]

0 = 0.04588315
1 = 0.03837648
2 = 0.023338
3 = 0.00996766
4 = 0.0099995
5 = 0.01001755
6 = 0.00813411
7 = 0.00379978

#mzml文件预测参数
[mzml]
vendor = ''
n_jobs = 4#并行处理的核数
min_intensity = 100 #并非相对强度，An intensity threshold of 100  was used to eliminate electronic noise.
precursor_error = 0.8#质荷比误差
ROI_identify_method = 'DDA' #DDA:ms2fms1 algorithm; 'MS1': centWave algorith
min_element_roi = 3 #roi识别中MS1_index的最少元素数量
min_element_sum = 3 #halo_eval中count_list中最少元素数量

#可视化参数
[visualization]
path = "C:\\Users\\xyy\\Desktop\\python\\HaloAnalyzer_training\\test1"
