#此文件为配置文件，用于配置模型训绨集相关参数

#训练集相关参数
[datasets]

paths = [
        ["E:/XinBackup/source_data/datasets/NPAtlas_download.json","mol_formula",],
    #    [   "D:/python/wangmengyuan/dataset/datasets/NPAtlas_download.json",
    #     "mol_formula",
    # ],
#    [
#         "D:/python/wangmengyuan/dataset/datasets/CFM-ID_metadata_DTXCID.csv",
#         "MS-Ready_Mol_Formula",
#     ],
#     [
#         "D:/python/wangmengyuan/dataset/datasets/hmdb_metabolites.csv",
#         "chemical_formula",
#     ],
#     [
#         "D:/python/wangmengyuan/dataset/datasets/uniqueNaturalProduct_formula_from_COCONUT.csv",
#         "Formula",
#     ],
#     [
#         "D:/python/wangmengyuan/dataset/datasets/ZINC_merged_data_dereplicated.csv",
#         "formula",
#     ],
#     [
#         "D:/python/wangmengyuan/dataset/datasets/ChEBI_database.csv",
#         "CHEMICAL_DATA",
#     ],
    
           
        ]#数据库文件路径
type_list = ['base']#生成数据库类型
element_list = ['C','H','O','N','P','Cl','Br','F','I','S','Fe','Se','B']#训练集中所包含的元素种类
mz_start = 50#质荷比起始值
mz_end = 3000#质荷比终止值
rate_for_hydro = [0.33,0.66,0.99,1.32,1.65,2.3,5]#模拟hydro所用的rate
return_from_max_ints = "True"#是否从最大强度的峰开始返回

#模型训练参数
[model_data]
#训练使用的特征列表
feature_list = [
                "p0_int",
                "p1_int",
                "p2_int",
                "p3_int",
                "p4_int",
                "p5_int",
                "p6_int",
                "m2_m1",
                "m1_m0",  
                ]

#训练使用的数据集
use_add_fe_data = "False"
use_add_b_data =  "False"
use_add_se_data =  "False"
use_hydroisomer_data = "False"

#模型训练参数
[model_construct]
train_batch = 4
val_batch = 4
classes = 8
epochs = 2
learning_rate = 0.0003

#模型训练权重
[model_construct_class_weight.classes_weight]
0 = 0.0081076
1 = 0.00688837
2 = 0.00505541
3 = 0.00803142
4 = 0.00783068
5 = 0.00810042
6 = 0.00342933
7 = 0.00379142

#mzml文件预测参数
[FeatureFinding]
ion_df_min_inty = 100

mass_trace_detection = [["mass_error_ppm", 20.0],
                        ['min_trace_length', 5.0],
                        ['noise_threshold_int', 100.0]]

elution_peak_detection = [['width_filtering','fixed']]

feature_detection = [['local_rt_range',10.0],
                     ['local_mz_range',6.5],
                     ['chrom_fwhm', 5.0],
                     ['enable_RT_filtering', 'true'],
                     ['mz_scoring_by_elements', 'true'],
                     ["elements", "CHNOPSClBrFeBSeIF"],
                     ["report_chromatograms", 'true'],
                     ['isotope_filtering_model','none'],
                     ["remove_single_traces", "true"],
                     ["report_convex_hulls", 'true']
                     ]
                    
[FeatureMapProcessor]
mz_error = 0.001
rt_error = 0.001
min_num_of_masstraces = 4
min_feature_int = 10000


#可视化参数
[visualization]
path = "C:\\Users\\xyy\\Desktop\\python\\HaloAnalyzer_training\\test1"
