[datasets]
paths = [
    [
        "E:/XinBackup/source_data/datasets/NPAtlas_download.json",
        "mol_formula",
    ],]
element_list = [
    "K",
    "F",
    "S",
    "N",
    "C",
    "As",
    "P",
    "I",
    "O",
    "Cl",
    "H",
    "Br",
    "Ho",
    "Na",
    "Al",]
mz_start = 200
mz_end = 2000
repeat_for_noise = 1
rate_for_hydro = [0.33,0.66]
rate_for_hydro2 = [0.99]
rate_for_hydro3 = [1.32,1.65]

[model_data]
feature_list = [
    "new_a0_ints",
    "new_a1_ints",
    "new_a2_ints",
    "new_a3_ints",
    "new_a2_a1_10"]
use_noise_data = "False"
use_add_fe_data = "True"
use_hydroisomer_data = "True"

[model_construct]
train_batch = 1000
val_batch = 1000

base_classes = 3
sub_classes = 5
hydro_classes = 8

epochs = 10
learning_rate = 0.001

[model_construct_class_weight.base_weight]
0 = 10
1 = 10
2 = 10

[model_construct_class_weight.sub_weight]
0 = 1
1 = 1
2 = 1
3 = 1

[model_construct_class_weight.hydroisomer_weight]
0 = 1
1 = 1
2 = 2
3 = 1
4 = 1
5 = 1
6 = 1
7 = 1

[asari]
min_prominence_threshold = 0.33
mz_tolerance_ppm = 10
min_intensity = 5000
min_timepoints = 5
min_peak_height = 5000

[mzml]
vendor = ''
min_intensity = 100
precursor_error = 0.3
ROI_identify_method = 'ms1ms2_linked'

[visualization]
path = "C:\\Users\\xyy\\Desktop\\python\\HaloAnalyzer_training\\test1"
