[datasets]
mz_start = 200
mz_end = 1600
element_list = [
    "K",
    "F",
    "S",
    "N",
    "C",
    "As",
    "P",
    "I",
    "O",
    "Cl",
    "H",
    "Br",
    "Ho",
    "Na",
    "Al",
    "Fe",
]
repeat = 1
feature_list = [
    "b_2",
    "b_1",
    "a1",
    "a2",
    "a3",
    "new_a0_ints",
    "new_a1_ints",
    "new_a2_ints",
]
paths = [
    [
        "D:/python/my_pick_halo_4/source_data/datasets/NPAtlas_download.json",
        "mol_formula",
    ],
]
rates = [
    0.33,
    0.5,
    1.0,
]

[model_data]
data_weight = 1
noise_data_weight = 1
add_fe_weight = 1
hydroisomer_weight = 1
use_noise_data = "False"
use_add_fe_data = "True"
use_hydroisomer_data = "False"

[model_construct]
train_batch = 1000
val_batch = 1000
dense1 = 4000
dense1_drop = 0.5
dense2 = 2000
dense2_drop = 0.3
dense3 = 500
classes = 4
epochs = 10

[model_construct_class_weight.base_weight]
0 = 100
1 = 10
2 = 10

[model_construct_class_weight.sub_weight]
0 = 20
1 = 20
2 = 4
3 = 1
4 = 0.1

[model_construct_class_weight.hydroisomer_weight]
0 = 30
1 = 10

[asari]
min_prominence_threshold = 0.33
mz_tolerance_ppm = 10
min_intensity = 5000
min_timepoints = 5
min_peak_height = 5000

[mzml]
min_intensity = 100

[visualization]
path = "C:\\Users\\xyy\\Desktop\\python\\HaloAnalyzer_training\\test1"
